[package]
name = "fdl"
version = "0.1.0"
authors = ["yoshitsugu <yoshitsugu@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "^0.5.1"
wasm-bindgen = "^0.2.58"
web-sys = "0.3.35"